### ISSUE TITLE
Your API key is public

### ISSUE THREAD

**Issue by cherylli** [shriya-tiwari/Reciplay_website#10]
In js/config

API keys should not be committed to a public repository

**Comment by SRIMANKS** [comment]
I can work on this but what should I do then instead of putting API in the public repository? can you assign me this?

**Comment by cherylli** [comment]
I'm not the owner of this repo. I just came to checked it out and saw the API is publicly accessible. 

Normally you would put something like API keys in the environment variables or just a  file not pushed to github

**Comment by shriya-tiwari** [comment]
Its fine, if a front end project requires the API key to be publicly accessible for open source contribution, I should not bohter making it hidden in .gitignore file. Otherwise it becomes difficult for people to contribute.
