### ISSUE TITLE
No validations

### ISSUE THREAD

**Issue by vatsalsinghkv** [shriya-tiwari/Reciplay_website#21]
I'd like to fix this issue and add some features like **(assign this issue to me)**:
- It validates before adding ingredients to the our list
- Hover state to the ingredients

Results of no validations: 
Imagine if these things were getting added in the backend everyone would've seen them

<img width="1238" alt="Screenshot 2022-10-22 at 8 13 13 AM" src="https://user-images.githubusercontent.com/68834718/197315713-a3d2405d-1d30-496c-bc37-ede3d9f9a3b1.png">

<img width="1439" alt="Screenshot 2022-10-22 at 8 13 33 AM" src="https://user-images.githubusercontent.com/68834718/197315712-1ba4bac0-6cc2-47a4-ae15-9aa2dbda2e3c.png">

**Comment by shriya-tiwari** [comment]
go ahead 👍
