### ISSUE TITLE
No Error Handling

### ISSUE THREAD

**Issue by vatsalsinghkv** [shriya-tiwari/Reciplay_website#24]
I'd like to add error handling
If there's an error (no recipe  found), it'll be displayed with proper illustration

Current website looks something like this without error handling:
<img width="1440" alt="Screenshot 2022-10-22 at 11 00 53 PM" src="https://user-images.githubusercontent.com/68834718/197354329-349252f7-bc7d-4ed2-ab30-c605615a2eee.png">

I'd like to add something like this:
<img width="1437" alt="Screenshot 2022-10-22 at 11 02 30 PM" src="https://user-images.githubusercontent.com/68834718/197354361-6c57671f-cb8b-4331-a458-5ab04c897566.png">

**Comment by shriya-tiwari** [comment]
That would be great, go ahead !!
